FROM tomcat:9
#SSH 서버 설치
RUN apt-get update                                                                && \
    apt-get install -y openssh-server                                             && \
    echo 'root:1234' | chpasswd                                                   && \
    sed -ri 's/^#?PermitRootLogin\s+.*/PermitRootLogin yes/' /etc/ssh/sshd_config && \
    sed -ri 's/UsePAM yes/#UsePAM yes/g'                    /etc/ssh/sshd_config  && \
    mkdir /var/run/sshd                                                           && \
    apt-get clean

# tomcat 작업 공간 지정
WORKDIR /usr/local/tomcat
RUN cp -R ./webapps.dist/* ./webapps/
RUN sed -i '$d' /usr/local/tomcat/conf/tomcat-users.xml
RUN echo "  <role rolename=\"manager-gui\" />" >> /usr/local/tomcat/conf/tomcat-users.xml
RUN echo "  <role rolename=\"manager-script\" />" >> /usr/local/tomcat/conf/tomcat-users.xml
RUN echo "  <role rolename=\"manager-jmx\" />" >> /usr/local/tomcat/conf/tomcat-users.xml
RUN echo "  <role rolename=\"manager-status\" />" >> /usr/local/tomcat/conf/tomcat-users.xml
RUN echo "  <user username=\"admin\" password=\"admin\"  roles=\"manager-gui, manager-script, manager-jmx, manager-status\"/>" >> /usr/local/tomcat/conf/tomcat-users.xml
RUN echo "  <user username=\"deployer\" password=\"deployer\" roles=\"manager-script\"/>" >> /usr/local/tomcat/conf/tomcat-users.xml
RUN echo "  <user username=\"tomcat\" password=\"tomcat\"  roles=\"manager-gui\"/>" >> /usr/local/tomcat/conf/tomcat-users.xml
RUN echo "</tomcat-users>" >> /usr/local/tomcat/conf/tomcat-users.xml
RUN sed -i '/^  <Valve/d' /usr/local/tomcat/webapps/manager/META-INF/context.xml

RUN echo "export JAVA_HOME=/opt/java/openjdk"  >> /root/.bashrc

#SSH Service Port
EXPOSE 22
#Tomcat Service Port
EXPOSE 8080

#SSH 서비스 실행
CMD ["/usr/sbin/sshd", "-D"]

#tomcat 서비스는Jenkins shell 실행
# /usr/local/tomcat/bin/catalina.sh run &
#CMD ["catalina.sh", "run"]
